### ISSUE TITLE
perlito.org is not longer pointing at your content

### ISSUE THREAD

**Issue by grtodd** [fglock/Perlito#44]
perlito.org content seems no longer come from fglock.github.io

The quick fix would be to stop redirecting there from fglock.github.io  (this can be controlled from your DNS provider and [GH pages configuration](https://help.github.com/articles/quick-start-setting-up-a-custom-domain/)) until the issue can be "resolved".

http://fglock.github.io/Perlito/perlito/perlito5.html

**Comment by fglock** [comment]
Thaks for reporting. I've just removed the CNAME file, "
http://fglock.github.io/Perlito/ " should start working again soon.

2016-05-16 17:40 GMT+02:00 Graham Todd <notifications@github.com>:

**Comment by fglock** [comment]
This returns the project page now:
~~~bash
$ curl -v http://fglock.github.io/Perlito/
~~~
