### ISSUE TITLE
successive runs of perl code giving different resulsts  

### ISSUE THREAD

**Issue by Jerkwin** [fglock/Perlito#53]
Hi, I have a piece of perl code and run it using the online compiler, the first run gave the correct results, but if I click the `Excute` and run it again, the results change and are not correct now. I need to refresh the page to run again. Is there something like clearing all the memory for each run?

**Comment by shlomif** [comment]
On Thu, 07 Dec 2017 18:04:00 +0000 (UTC)
Jerkwin <notifications@github.com> wrote:

> Hi, I have a piece of perl code and run it using the online compiler, the
> first run gave the correct results, but if I click the `Excute` and run it
> again, the results change and are not correct now. I need to refresh the page
> to run again. Is there something like clearing all the memory for each run?
> 

Hi, can you share a sample problem code?

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/Google-Discontinues-Services/

A Zen master once asked Chuck Norris if he had the Buddha nature. Norris
proceeded by making sure the former master will lack any nature whatsoever.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by Jerkwin** [comment]
Thanks for your responses. I put a sample code at <https://github.com/Jerkwin/Jerkwin.github.io/blob/master/Prog/mktop>.

**Comment by fglock** [comment]
Yes, the global memory is not cleared between runs in the same browser window.

What happens here is that the script is not using "strict", and all variables are created by default in the global browser memory.

If you add this in the first line of the script:
`use strict;`
then you will see the problem:
`Global symbol "$txt" requires explicit package name at  line 2`

You don't necessarily have to use "strict" in your script, but you will have to initialize some variables.

**Comment by fglock** [comment]
I believe this is working correctly:
https://gist.github.com/fglock/7aea4fc6b47050bb6c097537dac85720

I've tested in http://fglock.github.io/Perlito/perlito/perlito5.html
as well as in the Perl command line.

Note: I've updated http://fglock.github.io/Perlito/perlito/perlito5.js
to fix a problem with the `$#` sigil.
You may have to reload the browser page to pick up the latest `perlito5.js`

**Comment by Jerkwin** [comment]
Thank you very much. it works now.
BTW, is it possible for you to release a minimized/uglified version of the perlito5.js, so that when it's used in the browser, it can be load faster?

**Comment by fglock** [comment]
Note that when you access the page using `https` it (usually) uses compression.

https://fglock.github.io/Perlito/perlito/perlito5.html

I've updated the links in the web pages to `https`.
