### ISSUE TITLE
Tests for perl 5.26 functionality, while package expects only Perl 5.14

### ISSUE THREAD

**Issue by jwrightecs** [fglock/Perlito#54]
t/regex_xx.t starts with use 5.26; requiring perl 5.26, but the minimum required version of Perl is only 5.14, causing tests to fail onl Perls 5.14 to 5.24.  Perhaps this test should be wrapped in a if ($^V ge v5.26) block, with the else sending a SKIP directive

**Comment by fglock** [comment]
thanks, this will be fixed in next CPAN version
