### ISSUE TITLE
Code examples on website don't compile

### ISSUE THREAD

**Issue by cygx** [fglock/Perlito#59]
The 'Perl5' and 'Perl5 to Perl6' code examples on the website fail to compile.

Hitting 'execute' on https://fglock.github.io/Perlito/perlito/perlito5.html results in

```
Compiling.
Error:
Value tokens must be separated by an operator (did you forget a comma?) at  line 14

Compilation aborted.
```

Hitting 'execute' on https://fglock.github.io/Perlito/perlito/perlito5to6.html results in

```
Compiling.
Error:
Bareword found where operator expected at  line 10

Compilation aborted.
```

The 'Perl6' example seems to work.

**Comment by fglock** [comment]
Thank you for reporting!
Recompiling and uploading the files solved the problem.

The following files were updated:

https://fglock.github.io/Perlito/perlito/perlito5.js

https://fglock.github.io/Perlito/perlito/perlito5to6.js
