### ISSUE TITLE
Other JS interpreters?

### ISSUE THREAD

**Issue by 3oheicrw** [fglock/Perlito#68]
Does code generated work with Mozilla JSShell and Microsoft ChakraCore?

https://ftp.mozilla.org/pub/firefox/releases/97.0b9/jsshell/

https://github.com/chakra-core/ChakraCore

**Comment by fglock** [comment]
Perlito JavaScript is not tested with Mozilla JSShell or with Microsoft
ChakraCore.
It is known to work in most browsers and with NodeJS.

Em sáb., 29 de jan. de 2022 às 13:22, 3oheicrw ***@***.***>
escreveu:
